export {About} from "./Page";
export {Home} from "./Home.jsx";
export {Admin} from './Login.jsx';
export {Dashboard} from "./Dashboard";
export {Dashboard} from "./Dashboard";
export {Questionnaire} from "./Questionnaire"
export {CrohnRisk} from "./CrohnRisk"
export {DiseaseInformationPage} from "./Crohninformation"
export {OptionalSurveyIntermidiare} from "./OptionalSurveyIntermidiare"